#! /usr/bin/env python

import numpy as np
import sys
import matplotlib.pyplot as plt
import subprocess

fname = sys.argv[1]
name = fname.split(".")[0]
subprocess.run(["./target/release/strauws", "-i", f"{name}"])

shape = np.loadtxt(f"./{name}.conf", delimiter=',', max_rows=1, dtype=int)
cwt_matrix = np.fromfile(f"./{name}.cwt", dtype='<f8').reshape(shape)

try:
    start = int(sys.argv[2])-1
    end = int(sys.argv[3])
except TypeError:
    start = -9
    end = -9

if start == -9:
    plt.imshow(cwt_matrix.T, cmap='viridis', aspect='auto', interpolation=None)
    plt.savefig(f"{name}.png")
else:
    plt.imshow(cwt_matrix.T[:, start:end], cmap='viridis', aspect='auto', interpolation=None)
    plt.savefig(f"{name}.png")